[package]
name = "yosari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
futures = "0.3.28"
sea-orm = {version = "0.12.1", features = ["sqlx-mysql", "runtime-tokio-native-tls", "macros"]}